# Generated by Django 6.0.6 on 2026-07-08 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('CONDITION', 'Condition'), ('ACTION', 'Action')], max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['workflow', 'order'], name='workflows_w_workflo_394b33_idx')],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'order'), name='unique_workflow_step_order')],
            },
        ),
    ]
