# Generated by Django 6.0.6 on 2026-07-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
