# Generated by Django 6.0.6 on 2026-07-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowstep_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='step_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('HTTP_REQUEST', 'HTTP Request'), ('WAIT', 'Wait')], max_length=20),
        ),
    ]
